ClothBazar/ClothBazar.web/Controllers/CategoryController.cs
using ClothBazar.Database;
using ClothBazar.Entities;
using ClothBazar.services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.web.Controllers
{
    public class CategoryController : Controller
    {
        Categoryservices categoryservice = new Categoryservices();
        // GET: Category
        public ActionResult Index()
        {
            var cate = categoryservice.getcategory();
            return View(cate);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(category cate)
        {
         
            categoryservice.savecategory(cate);


            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var category = categoryservice.getsanglecategory(Id);
            return View(category);
        }
        [HttpPost]
        public ActionResult Edit(category cate)
        {

            categoryservice.updatecategory(cate);


            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var category = categoryservice.getsanglecategory(Id);
            return View(category);
        }
        [HttpPost]
        public ActionResult Delete(category category)
        {
             category = categoryservice.getsanglecategory(category.ID);
            categoryservice.deletecategory(category);


            return RedirectToAction("Index");
        }
        
    }
}

ClothBazar/ClothBazar.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ClothBazar/ClothBazar.web/Controllers/productController.cs
using ClothBazar.Entities;
using ClothBazar.services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.web.Controllers
{
    public class productController : Controller
    {
        productservices productservic = new productservices();
        // GET: product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult producttable(string search)
        {
            var products = productservic.getproduct();
            if(string.IsNullOrEmpty(search)==false)
            {
                products = products.Where(p => p.Name.Contains(search)).ToList();
            }
           
            return PartialView(products);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(product product)
        {
            productservic.saveproduct(product);
            return RedirectToAction("producttable");
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var products = productservic.getsangleproduct(ID);
            return PartialView(products);
        }
        [HttpPost]
        public ActionResult Edit(product product)
        {
            productservic.updateproduct(product);
            return RedirectToAction("producttable");
        }
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            productservic.deleteproduct(ID);
            return RedirectToAction("producttable");
        }
    }
}

ClothBazar/ClothBazar.web/Views/Category/Create.cshtml
@model ClothBazar.Entities.category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClothBazar/ClothBazar.web/Views/Category/Delete.cshtml
@model ClothBazar.Entities.category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClothBazar/ClothBazar.web/Views/Category/Edit.cshtml
@model ClothBazar.Entities.category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClothBazar/ClothBazar.web/Views/Category/Index.cshtml
@model IEnumerable<ClothBazar.Entities.category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ClothBazar/ClothBazar.web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClothBazar/ClothBazar.web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ClothBazar/ClothBazar.web/Views/product/Create.cshtml
@model ClothBazar.Entities.product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClothBazar/ClothBazar.web/Views/product/Edit.cshtml
@model ClothBazar.Entities.product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@*@using (Html.BeginForm("Edit", "product",new {@id = "editform" }))
{*@
<form id="editform">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="updatebtn" value="update" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    $("#updatebtn").click(function () {

        $.ajax({
            url: '/product/Edit',
            type: 'post',
            data: $("#editform").serialize()
            //data: yourData,
            //datatype: 'json'
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
                $("#actioncontainer").html("");
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
</script>

ClothBazar/ClothBazar.web/Views/product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="tablecontainer">
    @{
        Html.RenderAction("producttable");
        //Html.RenderAction("Create");
    }
</div>
<div id="actioncontainer">

</div>

ClothBazar/ClothBazar.web/Views/product/producttable.cshtml
@model IEnumerable<ClothBazar.Entities.product>

@{
    ViewBag.Title = "producttable";
}
<br />
<br />
<form>
    
    <input name="search" id="srchtxt" />
    <button type="button" id="srchbtn">search</button>
    @*@Html.ActionLink("Create New", "Create")*@
    <input type="button" id="newbtn"  value="new"/>
    
</form>
<br />
<br />
<div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new {data_id = item.ID,@class="editbtn"})*@ 
                    <button class="editbtn" data_id="@item.ID">Edit</button>|
                    @*@Html.ActionLink("Details", "Details", new { id = item.ID })*@
                    <button class="deletbtn" data_id="@item.ID">Delete</button>|
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                </td>
            </tr>
        }

    </table>
</div>

<script>
    $("#srchbtn").click(function () {
        var searchvalue = $("#srchtxt").val();
        $.ajax({
            url: '/product/producttable',
            type:'post',
            data: {
                search:searchvalue
            }
            //data: yourData,
            //datatype: 'json'
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
    $(".editbtn").click(function () {
    
        $.ajax({

            url: '/product/Edit',
            data: {
                ID: $(this).attr('data_id')

            }
            
            //data: yourData,
            //datatype: 'json'
        })
            .done(function (response) {
                $("#actioncontainer").html(response);
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
    $("#newbtn").click(function () {

        $.ajax({

            url: '/product/Create',


            //data: yourData,
            //datatype: 'json'
        })
            .done(function (response) {
                $("#actioncontainer").html(response);
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
    $(".deletbtn").click(function () {
        var confirmDelet = confirm("are you sure you want to delete this");
        if (confirmDelet) {


            $.ajax({
                type: 'post',
                url: '/product/Delete',
                data: {
                    ID: $(this).attr('data_id')

                }

                //data: yourData,
                //datatype: 'json'
            })
                .done(function (response) {
                    $("#tablecontainer").html(response);
                })

                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("fail");
                });
        }
        });
   
</script>